version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)-20s : [thread - %(threadName)s] [%(levelname)-3s] : %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers:
    - console